apiVersion: v1
kind: Namespace
metadata:
  name: security-pipeline
  labels:
    app.kubernetes.io/part-of: autonomous-threat-remediation-pipeline
---

apiVersion: v1
kind: Namespace
metadata:
  name: demo-workloads
  labels:
    app.kubernetes.io/part-of: autonomous-threat-remediation-pipeline
