apiVersion: v1
kind: ServiceAccount
metadata:
  name: remediation-agent-sa
  namespace: security-pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: remediation-agent-role
  namespace: demo-workloads
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["networkpolicies"]
    verbs: ["get", "list", "watch", "create", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: remediation-agent-binding
  namespace: demo-workloads
subjects:
  - kind: ServiceAccount
    name: remediation-agent-sa
    namespace: security-pipeline
roleRef:
  kind: Role
  name: remediation-agent-role
  apiGroup: rbac.authorization.k8s.io
